export const questionsSeed = [
  {
    slug: 'vars-what-is-variable',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is a variable in JavaScript?',
    choices: [
      { id: 'a', text: 'A named container that can store a value' },
      { id: 'b', text: 'A function that always returns a value' },
      { id: 'c', text: 'A file that contains code' },
      { id: 'd', text: 'A special type of loop' },
    ],
    answer: 'a',
    tip1: 'Think of a label attached to a value.',
    tip2: 'Variables let you read and write a value by name.',
    explanationShort: 'A variable is a named container for a value that you can read and update.',
    references: ['MDN: JavaScript variables'],
    answerDocBlockAnchor: 'what-is-a-variable',
  },
  {
    slug: 'vars-micro-what-is-variable',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which sentence best describes a variable?',
    choices: [
      { id: 'a', text: 'A named container that can store a value' },
      { id: 'b', text: 'A loop that repeats forever' },
      { id: 'c', text: 'A built-in JavaScript keyword' },
      { id: 'd', text: 'A CSS rule for styling' },
    ],
    answer: 'a',
    tip1: 'Think “label + value.”',
    explanationShort: 'A variable is a named container that holds a value you can read or change.',
    references: ['MDN: JavaScript variables'],
    answerDocBlockAnchor: 'what-is-a-variable',
  },
  {
    slug: 'vars-declare-vs-initialize',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which statement initializes a variable?',
    choices: [
      { id: 'a', text: 'let count;' },
      { id: 'b', text: 'let count = 0;' },
      { id: 'c', text: 'count;' },
      { id: 'd', text: 'var;' },
    ],
    answer: 'b',
    tip1: 'Initialization assigns the first value.',
    tip2: 'Look for the `=` operator with a value.',
    explanationShort: '`let count = 0;` declares and initializes the variable.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'declaring-vs-initializing',
  },
  {
    slug: 'vars-let-reassign',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which statement about `let` is true?',
    choices: [
      { id: 'a', text: '`let` creates a constant that cannot change' },
      { id: 'b', text: '`let` allows reassignment' },
      { id: 'c', text: '`let` is function-scoped only' },
      { id: 'd', text: '`let` is only for numbers' },
    ],
    answer: 'b',
    tip1: 'Think: `let` = reassignable.',
    tip2: '`let` is block-scoped but still mutable.',
    explanationShort: '`let` allows reassignment and is block-scoped.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'let-basics',
  },
  {
    slug: 'vars-micro-let-basics',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which line correctly uses `let`?',
    choices: [
      { id: 'a', text: 'let score = 5; score = 6;' },
      { id: 'b', text: 'let score = 5; let score = 6;' },
      { id: 'c', text: 'let = 5;' },
      { id: 'd', text: 'let score := 5;' },
    ],
    answer: 'a',
    tip1: 'Reassigning is allowed; redeclaring is not.',
    explanationShort: 'You can reassign a let variable, but you cannot redeclare it in the same scope.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'let-basics',
  },
  {
    slug: 'vars-var-legacy',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Why is `var` considered legacy in new code?',
    choices: [
      { id: 'a', text: 'It creates block-scoped variables' },
      { id: 'b', text: 'It has confusing scoping and hoisting behavior' },
      { id: 'c', text: 'It cannot be used in functions' },
      { id: 'd', text: 'It is required for constants' },
    ],
    answer: 'b',
    tip1: 'Think about scope and hoisting surprises.',
    tip2: '`var` behaves differently from `let` in blocks.',
    explanationShort: '`var` is function-scoped and hoisted, which can cause unexpected behavior.',
    references: ['MDN: var'],
    answerDocBlockAnchor: 'var-basics',
  },
  {
    slug: 'vars-micro-var-basics',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Why can `var` feel surprising in blocks?',
    choices: [
      { id: 'a', text: 'It is block-scoped just like let' },
      { id: 'b', text: 'It is function-scoped and ignores blocks' },
      { id: 'c', text: 'It is only allowed inside classes' },
      { id: 'd', text: 'It only works in strict mode' },
    ],
    answer: 'b',
    tip1: 'Think “function scope.”',
    explanationShort: '`var` ignores block scope, so it stays visible outside blocks.',
    references: ['MDN: var'],
    answerDocBlockAnchor: 'var-basics',
  },
  {
    slug: 'vars-block-vs-function',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which statement best describes `let` scope?',
    choices: [
      { id: 'a', text: 'Function scope only' },
      { id: 'b', text: 'Block scope' },
      { id: 'c', text: 'Global scope only' },
      { id: 'd', text: 'Module scope only' },
    ],
    answer: 'b',
    tip1: 'A block is anything inside `{ }`.',
    tip2: '`let` respects block boundaries.',
    explanationShort: '`let` is block-scoped, meaning it exists only inside the nearest `{ }`.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'block-scope-vs-function-scope',
  },
  {
    slug: 'vars-micro-hoisting',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'What value does `var` have before it is assigned?',
    choices: [
      { id: 'a', text: 'null' },
      { id: 'b', text: 'undefined' },
      { id: 'c', text: '0' },
      { id: 'd', text: 'ReferenceError' },
    ],
    answer: 'b',
    tip1: 'Hoisted var is initialized to a default value.',
    explanationShort: '`var` is hoisted and initialized to undefined before assignment.',
    references: ['MDN: var'],
    answerDocBlockAnchor: 'hoisting-high-level',
  },
  {
    slug: 'vars-naming-tip',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which variable name follows common JavaScript naming conventions?',
    choices: [
      { id: 'a', text: 'user_name' },
      { id: 'b', text: 'UserName' },
      { id: 'c', text: 'userName' },
      { id: 'd', text: 'user-name' },
    ],
    answer: 'c',
    tip1: 'camelCase is standard for variables and functions.',
    tip2: 'Start lowercase, capitalize new words.',
    explanationShort: '`userName` is camelCase, the usual naming convention for variables.',
    references: ['MDN: JavaScript naming conventions'],
    answerDocBlockAnchor: 'naming-and-typo-tips',
  },
  {
    slug: 'vars-micro-common-mistake',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which line creates an accidental global in sloppy mode?',
    choices: [
      { id: 'a', text: 'let score = 10;' },
      { id: 'b', text: 'const score = 10;' },
      { id: 'c', text: 'score = 10;' },
      { id: 'd', text: 'var score = 10;' },
    ],
    answer: 'c',
    tip1: 'Missing a declaration keyword can leak globals.',
    explanationShort: 'Assigning to a name without declaring it can create a global variable.',
    references: ['MDN: Strict mode'],
    answerDocBlockAnchor: 'common-mistakes',
  },
  {
    slug: 'vars-common-mistake-global',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is a common mistake that creates accidental globals?',
    choices: [
      { id: 'a', text: 'Using `const`' },
      { id: 'b', text: 'Forgetting `let`/`const`/`var`' },
      { id: 'c', text: 'Using camelCase' },
      { id: 'd', text: 'Declaring in a block' },
    ],
    answer: 'b',
    tip1: 'Look for missing keywords.',
    tip2: 'Assignments without declarations can leak to global scope.',
    explanationShort: 'Assigning to a name without `let/const/var` can create a global variable.',
    references: ['MDN: Strict mode'],
    answerDocBlockAnchor: 'common-mistakes',
  },
  {
    slug: 'vars-let-reassign-output',
    difficulty: 'basic',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'let count = 1;\ncount = 2;\nconsole.log(count);',
    answer: '2',
    tip1: '`let` allows reassignment.',
    tip2: 'The last assigned value is logged.',
    explanationShort: '`count` is reassigned to 2, so the output is 2.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'let-basics',
  },
  {
    slug: 'vars-var-block-output',
    difficulty: 'basic',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'if (true) {\n  var x = 1;\n}\nconsole.log(x);',
    answer: '1',
    tip1: '`var` ignores block scope.',
    tip2: 'The variable is still visible outside the block.',
    explanationShort: '`var` is function-scoped, so `x` is visible and logs 1.',
    references: ['MDN: var'],
    answerDocBlockAnchor: 'block-scope-vs-function-scope',
  },
  {
    slug: 'vars-declare-then-assign',
    difficulty: 'basic',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'let score;\nscore = 7;\nconsole.log(score);',
    answer: '7',
    tip1: 'You can declare first, then assign later.',
    tip2: 'The current value is printed.',
    explanationShort: 'The variable is assigned 7, so it logs 7.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'declaring-vs-initializing',
  },
  {
    slug: 'vars-code-fix-hello-campfire',
    difficulty: 'basic',
    type: 'code',
    phase: 'quiz',
    prompt: 'Fix the code so it prints “Hello, Campfire!” in the console.',
    files: [
      {
        name: 'main.js',
        language: 'js',
        content: "let greeting = \"Hello, Campfire!\";\nconsole.log(greetin);",
      },
    ],
    expected: { mode: 'consoleIncludes', value: 'Hello, Campfire!' },
    answer: 'Hello, Campfire!',
    tip1: 'Check the variable name spelling; use camelCase consistently.',
    explanationShort: 'The variable name must match; once fixed, the console prints the greeting.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'naming-and-typo-tips',
  },
  {
    slug: 'vars-code-display-name-level',
    difficulty: 'basic',
    type: 'code',
    phase: 'quiz',
    prompt: 'Create two variables: name and level, then log “Ada — Level 1”.',
    files: [
      {
        name: 'main.js',
        language: 'js',
        content: "const name = \"Ada\";\nconst level = 1;\nconsole.log(`${name} — Level ${level}`);",
      },
    ],
    expected: { mode: 'consoleIncludes', value: 'Ada — Level 1' },
    answer: 'Ada — Level 1',
    tip1: 'Use template literals or string concatenation to match the exact format.',
    explanationShort: 'Combine the variables so the console reads “Ada — Level 1”.',
    references: ['MDN: Template literals'],
    answerDocBlockAnchor: 'declaring-vs-initializing',
  },
  {
    slug: 'vars-hoisting-correct',
    difficulty: 'medium',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which statement about hoisting is correct?',
    choices: [
      { id: 'a', text: '`var` is hoisted and initialized to undefined' },
      { id: 'b', text: '`let` is hoisted and initialized to undefined' },
      { id: 'c', text: '`var` is block-scoped' },
      { id: 'd', text: '`let` can be used before declaration' },
    ],
    answer: 'a',
    tip1: 'Think about what happens before assignment.',
    tip2: '`let` has a temporal dead zone.',
    explanationShort: '`var` declarations are hoisted and initialized to undefined.',
    references: ['MDN: var hoisting'],
    answerDocBlockAnchor: 'hoisting-high-level',
  },
  {
    slug: 'vars-block-scope-choice',
    difficulty: 'medium',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'After this block runs, which name is still accessible?\n\nif (true) { let a = 1; var b = 2; }',
    choices: [
      { id: 'a', text: 'a only' },
      { id: 'b', text: 'b only' },
      { id: 'c', text: 'both a and b' },
      { id: 'd', text: 'neither a nor b' },
    ],
    answer: 'b',
    tip1: '`let` stays inside the block.',
    tip2: '`var` ignores block boundaries.',
    explanationShort: '`b` is function-scoped, so it remains accessible.',
    references: ['MDN: let', 'MDN: var'],
    answerDocBlockAnchor: 'block-scope-vs-function-scope',
  },
  {
    slug: 'vars-redeclare-let',
    difficulty: 'medium',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which line causes an error?',
    choices: [
      { id: 'a', text: 'let user = "Ada"; user = "Lin";' },
      { id: 'b', text: 'let user = "Ada"; let user = "Lin";' },
      { id: 'c', text: 'var user = "Ada"; var user = "Lin";' },
      { id: 'd', text: 'let user = "Ada"; user++;' },
    ],
    answer: 'b',
    tip1: 'Redeclaring `let` in the same scope is not allowed.',
    tip2: 'Reassigning is allowed; redeclaring is not.',
    explanationShort: 'Redeclaring a `let` variable in the same scope throws an error.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'common-mistakes',
  },
  {
    slug: 'vars-var-hoisting-output',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'console.log(score);\nvar score = 5;',
    answer: 'undefined',
    tip1: '`var` declarations are hoisted.',
    tip2: 'The value is assigned after the log.',
    explanationShort: '`var score` is hoisted and initialized to undefined before assignment.',
    references: ['MDN: var hoisting'],
    answerDocBlockAnchor: 'hoisting-high-level',
  },
  {
    slug: 'vars-function-scope-output',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'function demo() {\n  if (true) {\n    var n = 3;\n  }\n  console.log(n);\n}\n\ndemo();',
    answer: '3',
    tip1: '`var` is function-scoped.',
    tip2: 'The variable survives the block.',
    explanationShort: '`n` is visible inside the function, so it logs 3.',
    references: ['MDN: var'],
    answerDocBlockAnchor: 'var-basics',
  },
  {
    slug: 'boss-campfire-declare-initialize',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'Which line declares and initializes a variable?',
    choices: [
      { id: 'a', text: 'let score;' },
      { id: 'b', text: 'let score = 0;' },
      { id: 'c', text: 'score = 0;' },
      { id: 'd', text: 'var;' },
    ],
    answer: 'b',
    tip1: 'Initialization includes a first value.',
    tip2: 'Look for the equals sign with a value.',
    explanationShort: '`let score = 0;` declares the variable and assigns its first value.',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'declaring-vs-initializing',
  },
  {
    slug: 'boss-campfire-let-block-output',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'What does this code print?',
    code: 'if (true) {\n  let lamp = "on";\n}\nconsole.log(typeof lamp);',
    answer: 'undefined',
    tip1: '`let` stays inside the block.',
    tip2: 'Outside the block, the name is not defined.',
    explanationShort: '`lamp` is block-scoped, so `typeof lamp` returns "undefined".',
    references: ['MDN: let'],
    answerDocBlockAnchor: 'block-scope-vs-function-scope',
  },
  {
    slug: 'boss-campfire-var-hoist-output',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'What does this code print?',
    code: 'console.log(flag);\nvar flag = "ready";',
    answer: 'undefined',
    tip1: '`var` declarations are hoisted.',
    tip2: 'The assignment happens after the log.',
    explanationShort: 'The declaration is hoisted, so the log sees undefined.',
    references: ['MDN: var'],
    answerDocBlockAnchor: 'hoisting-high-level',
  },
  {
    slug: 'boss-campfire-naming-choice',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'Which variable name is clearest and most consistent?',
    choices: [
      { id: 'a', text: 'n' },
      { id: 'b', text: 'userScore' },
      { id: 'c', text: 'User_Score' },
      { id: 'd', text: 'uS' },
    ],
    answer: 'b',
    tip1: 'Prefer descriptive camelCase names.',
    tip2: 'Short or mixed styles are harder to read.',
    explanationShort: '`userScore` is descriptive and follows camelCase naming.',
    references: ['MDN: JavaScript naming conventions'],
    answerDocBlockAnchor: 'naming-and-typo-tips',
  },
  {
    slug: 'vars-advanced-scope-output',
    difficulty: 'advanced',
    type: 'code_output',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'What does this code print?',
    code: 'var x = 10;\nfunction test() {\n  if (true) {\n    var x = 20;\n    let y = 30;\n  }\n  console.log(x, typeof y);\n}\n\ntest();\nconsole.log(x);',
    answer: '20 undefined\n10',
    tip1: '`var` inside a function overwrites the outer variable in that function.',
    tip2: '`let` stays inside the block; `typeof` outside returns "undefined".',
    explanationShort: 'Inside the function, `x` is 20 and `y` is out of scope. Outside, `x` remains 10.',
    references: ['MDN: var', 'MDN: let'],
    answerDocBlockAnchor: 'block-scope-vs-function-scope',
  },
] as const

export const constQuestionsSeed = [
  {
    slug: 'q-const-micro-initializer-required',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which const declaration is valid?',
    choices: [
      { id: 'a', text: 'const total;' },
      { id: 'b', text: 'const total = 0;' },
      { id: 'c', text: 'const = 0;' },
      { id: 'd', text: 'const let = 3;' },
    ],
    answer: 'b',
    tip1: 'const must be initialized right away.',
    tip2: 'Look for a value on the same line.',
    explanationShort: '`const total = 0;` both declares and initializes the constant.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'const-requires-initializer',
  },
  {
    slug: 'q-const-micro-mutation-vs-reassign',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which action is allowed with a const object?',
    choices: [
      { id: 'a', text: 'Reassign the whole object' },
      { id: 'b', text: 'Change a property value' },
      { id: 'c', text: 'Declare without a value' },
      { id: 'd', text: 'Use const inside a block' },
    ],
    answer: 'b',
    tip1: 'const blocks reassignment, not mutation.',
    tip2: 'You can change properties on the same object.',
    explanationShort: 'You can mutate object properties even when the binding is const.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'reassignment-vs-mutation',
  },
  {
    slug: 'q-const-micro-naming-style',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'micro',
    prompt: 'Which name is best for a regular const variable?',
    choices: [
      { id: 'a', text: 'MAX_SPEED' },
      { id: 'b', text: 'userScore' },
      { id: 'c', text: 'User_Score' },
      { id: 'd', text: 'user-score' },
    ],
    answer: 'b',
    tip1: 'Most const variables use camelCase.',
    tip2: 'UPPER_SNAKE_CASE is for true constants.',
    explanationShort: '`userScore` follows camelCase, the default naming for const variables.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'naming-constants',
  },
  {
    slug: 'q-const-what-is-const',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What does `const` create?',
    choices: [
      { id: 'a', text: 'A block-scoped binding that cannot be reassigned' },
      { id: 'b', text: 'A global variable that can be changed later' },
      { id: 'c', text: 'A function-scoped variable only' },
      { id: 'd', text: 'An immutable value' },
    ],
    answer: 'a',
    tip1: 'Think “binding, not value.”',
    tip2: 'const is block-scoped and not reassignable.',
    explanationShort: '`const` creates a block-scoped binding that cannot be reassigned.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'what-is-const',
  },
  {
    slug: 'q-const-reassign-typeerror',
    difficulty: 'basic',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'const score = 5;\ntry {\n  score = 7;\n} catch (err) {\n  console.log(err.name);\n}',
    answer: 'TypeError',
    tip1: 'Reassigning a const throws at runtime.',
    tip2: 'The error name is logged.',
    explanationShort: 'Reassigning a const variable throws a TypeError.',
    references: ['MDN: const', 'MDN: TypeError'],
    answerDocBlockAnchor: 'common-mistakes-const',
  },
  {
    slug: 'q-const-init-syntaxerror',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What happens with `const total;`?',
    choices: [
      { id: 'a', text: 'It declares a const with value undefined' },
      { id: 'b', text: 'It throws a SyntaxError' },
      { id: 'c', text: 'It becomes a global variable' },
      { id: 'd', text: 'It creates a mutable variable' },
    ],
    answer: 'b',
    tip1: 'const requires a value at declaration.',
    tip2: 'Missing initializer is a syntax error.',
    explanationShort: '`const` declarations must be initialized, so this is a SyntaxError.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'const-requires-initializer',
  },
  {
    slug: 'q-const-when-use-let',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'When should you use `let` instead of `const`?',
    choices: [
      { id: 'a', text: 'When the variable will be reassigned' },
      { id: 'b', text: 'When the value is a string' },
      { id: 'c', text: 'When the variable is global' },
      { id: 'd', text: 'When the code is inside a block' },
    ],
    answer: 'a',
    tip1: 'Use let only if you need to rebind.',
    tip2: 'Otherwise prefer const.',
    explanationShort: 'Use let when the variable needs reassignment; otherwise prefer const.',
    references: ['MDN: const', 'MDN: let'],
    answerDocBlockAnchor: 'when-to-use-const',
  },
  {
    slug: 'q-const-prefer-by-default',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is the best default choice for variables you do not reassign?',
    choices: [
      { id: 'a', text: 'var' },
      { id: 'b', text: 'const' },
      { id: 'c', text: 'let' },
      { id: 'd', text: 'global' },
    ],
    answer: 'b',
    tip1: 'Prefer the safest option by default.',
    tip2: 'Use let only when you must reassign.',
    explanationShort: 'Use const by default and switch to let only if reassignment is required.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'when-to-use-const',
  },
  {
    slug: 'q-const-code-use-const-let',
    difficulty: 'basic',
    type: 'code',
    phase: 'quiz',
    prompt: 'Change the code to use const for TAX_RATE and let for total, then run it.',
    files: [
      {
        name: 'main.js',
        language: 'js',
        content:
          "let TAX_RATE = 0.08;\nconst total = 100;\n// total should be able to change\ntotal = total + 10;\nconst final = total + total * TAX_RATE;\nconsole.log(`Total: ${final.toFixed(2)}`);",
      },
    ],
    expected: { mode: 'consoleIncludes', value: 'Total:' },
    answer: 'Total:',
    tip1: 'Values that never change should be const; totals that change should be let.',
    explanationShort: 'Using const for TAX_RATE and let for total avoids reassignment errors.',
    references: ['MDN: const', 'MDN: let'],
    answerDocBlockAnchor: 'when-to-use-const',
  },
  {
    slug: 'q-const-code-mutation-not-reassign',
    difficulty: 'basic',
    type: 'code',
    phase: 'quiz',
    prompt: 'Make the object mutation work but prevent reassignment errors.',
    files: [
      {
        name: 'main.js',
        language: 'js',
        content:
          "const settings = { theme: \"forest\" };\nsettings.theme = \"night\";\n// Remove or comment the line below to avoid reassignment errors\nsettings = {};\nconsole.log(`theme: ${settings.theme}`);",
      },
    ],
    expected: { mode: 'consoleIncludes', value: 'theme: night' },
    answer: 'theme: night',
    tip1: 'const prevents reassignment, not mutation of object properties.',
    explanationShort: 'Leave the mutation line and remove the reassignment; the console should show “theme: night”.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'reassignment-vs-mutation',
  },
  {
    slug: 'q-const-array-push-allowed',
    difficulty: 'basic',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'const items = ["map"];\nitems.push("torch");\nconsole.log(items.length);',
    answer: '2',
    tip1: 'const blocks reassignment, not mutation.',
    tip2: 'push changes the array contents.',
    explanationShort: 'Mutation is allowed, so the array length becomes 2.',
    references: ['MDN: Array.push', 'MDN: const'],
    answerDocBlockAnchor: 'const-with-objects-arrays',
  },
  {
    slug: 'q-const-object-prop-change-allowed',
    difficulty: 'basic',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'const hero = { name: "Ada" };\nhero.name = "Lin";\nconsole.log(hero.name);',
    answer: 'Lin',
    tip1: 'Property updates are allowed on const objects.',
    tip2: 'You are not reassigning the object.',
    explanationShort: 'The object is mutated, so the name becomes "Lin".',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'const-with-objects-arrays',
  },
  {
    slug: 'q-const-reassign-array-not-allowed',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'const bag = ["rope"];\ntry {\n  bag = [];\n} catch (err) {\n  console.log(err.name);\n}',
    answer: 'TypeError',
    tip1: 'Reassigning a const triggers a TypeError.',
    tip2: 'The error name is logged.',
    explanationShort: 'Reassigning the const binding throws a TypeError.',
    references: ['MDN: const', 'MDN: TypeError'],
    answerDocBlockAnchor: 'reassignment-vs-mutation',
  },
  {
    slug: 'boss-campfire-const-initializer',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'Which const declaration is valid?',
    choices: [
      { id: 'a', text: 'const gems;' },
      { id: 'b', text: 'const gems = 3;' },
      { id: 'c', text: 'const = 3;' },
      { id: 'd', text: 'const let = 3;' },
    ],
    answer: 'b',
    tip1: 'const must be initialized right away.',
    tip2: 'Look for a value on the same line.',
    explanationShort: '`const gems = 3;` declares and initializes the constant.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'const-requires-initializer',
  },
  {
    slug: 'boss-campfire-const-mutation',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'What does this code print?',
    code: 'const bag = { items: 1 };\nbag.items += 1;\nconsole.log(bag.items);',
    answer: '2',
    tip1: 'const blocks reassignment, not mutation.',
    tip2: 'Property updates are allowed.',
    explanationShort: 'The object is mutated, so items becomes 2.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'reassignment-vs-mutation',
  },
  {
    slug: 'boss-campfire-const-let-choice',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'Which line should use let instead of const?',
    choices: [
      { id: 'a', text: 'const title = "Guide";' },
      { id: 'b', text: 'let count = 0; count++;' },
      { id: 'c', text: 'const settings = { mode: "dark" };' },
      { id: 'd', text: 'const maxLives = 3;' },
    ],
    answer: 'b',
    tip1: 'Use let when the binding changes.',
    tip2: 'Counters are a classic let case.',
    explanationShort: 'The counter is reassigned, so let is appropriate.',
    references: ['MDN: let', 'MDN: const'],
    answerDocBlockAnchor: 'const-vs-let-decision',
  },
  {
    slug: 'boss-campfire-const-scope-output',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'What does this code print?',
    code: 'try {\n  if (true) {\n    const level = 5;\n  }\n  console.log(level);\n} catch (err) {\n  console.log(err.name);\n}',
    answer: 'ReferenceError',
    tip1: 'const is block-scoped.',
    tip2: 'Accessing it outside the block throws.',
    explanationShort: '`level` is out of scope, so a ReferenceError is logged.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'common-mistakes-const',
  },
  {
    slug: 'q-const-true-constant-uppercase',
    difficulty: 'medium',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which name is best for a true constant?',
    choices: [
      { id: 'a', text: 'maxLives' },
      { id: 'b', text: 'MAX_LIVES' },
      { id: 'c', text: 'MaxLives' },
      { id: 'd', text: 'max-lives' },
    ],
    answer: 'b',
    tip1: 'Use UPPER_SNAKE_CASE for true constants.',
    tip2: 'Think config values or fixed invariants.',
    explanationShort: 'UPPER_SNAKE_CASE is reserved for true constants like config values.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'naming-constants',
  },
  {
    slug: 'q-const-common-misconception-immutable',
    difficulty: 'medium',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which statement about const is true?',
    choices: [
      { id: 'a', text: 'const makes values immutable' },
      { id: 'b', text: 'const prevents reassignment, not mutation' },
      { id: 'c', text: 'const works only for numbers' },
      { id: 'd', text: 'const is function-scoped' },
    ],
    answer: 'b',
    tip1: 'Think about binding vs value.',
    tip2: 'Objects can still change.',
    explanationShort: 'const prevents reassignment of the binding, but objects/arrays can mutate.',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'common-mistakes-const',
  },
  {
    slug: 'q-const-block-scope-output',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'let result;\ntry {\n  if (true) {\n    const level = 3;\n  }\n  console.log(level);\n} catch (err) {\n  result = err.name;\n}\nconsole.log(result);',
    answer: 'ReferenceError',
    tip1: 'const is block-scoped.',
    tip2: 'Accessing it outside throws a ReferenceError.',
    explanationShort: 'The variable is out of scope, so the code logs "ReferenceError".',
    references: ['MDN: const'],
    answerDocBlockAnchor: 'common-mistakes-const',
  },
  {
    slug: 'q-const-vs-let-decision',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which line should use `let` instead of `const`?',
    choices: [
      { id: 'a', text: 'const theme = "forest";' },
      { id: 'b', text: 'const limit = 10;' },
      { id: 'c', text: 'let index = 0; index++;' },
      { id: 'd', text: 'const hero = { name: "Ada" };' },
    ],
    answer: 'c',
    tip1: 'Use let when the binding changes.',
    tip2: 'Counters are typical let cases.',
    explanationShort: 'Counters that change should use let, not const.',
    references: ['MDN: let', 'MDN: const'],
    answerDocBlockAnchor: 'const-vs-let-decision',
  },
  {
    slug: 'q-const-boss-mutation-scope-trick',
    difficulty: 'advanced',
    type: 'code_output',
    phase: 'boss',
    rankSlug: 'campfire-cadet',
    prompt: 'What does this code print?',
    code: 'const pack = ["map"];\nif (true) {\n  const pack = ["rope"];\n  pack.push("torch");\n  console.log(pack.join(","));\n}\ntry {\n  pack = [];\n} catch (err) {\n  console.log(err.name);\n}\npack.push("flint");\nconsole.log(pack.length);',
    answer: 'rope,torch\nTypeError\n2',
    tip1: 'Inner const shadows the outer binding.',
    tip2: 'The outer binding cannot be reassigned, but it can be mutated.',
    explanationShort: 'The inner pack logs its contents, reassignment throws TypeError, and the outer array length becomes 2.',
    references: ['MDN: const', 'MDN: Array.push'],
    answerDocBlockAnchor: 'reassignment-vs-mutation',
  },
] as const

export const prologueWelcomeQuestions = [] as const

export const prologueFinalQuestions = [
  {
    slug: 'prologue-final-js-adds-behavior',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What does JavaScript add to a web page?',
    choices: [
      { id: 'a', text: 'Only colors and fonts' },
      { id: 'b', text: 'Behavior and logic' },
      { id: 'c', text: 'Only images' },
      { id: 'd', text: 'Only layout grids' },
    ],
    answer: 'b',
    tip1: 'Think interaction and decisions.',
    explanationShort: 'JavaScript adds behavior and logic to web pages.',
    references: ['JavaScriptopia: Welcome'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-welcome',
    answerDocBlockAnchor: 'welcome-to-javascriptopia',
  },
  {
    slug: 'prologue-final-learn-vs-challenge',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'In Learn Mode you should:',
    choices: [
      { id: 'a', text: 'Skip the docs and only guess' },
      { id: 'b', text: 'Read the scrollbook, then take the quiz' },
      { id: 'c', text: 'Disable teleport' },
      { id: 'd', text: 'Only use the sidebar' },
    ],
    answer: 'b',
    tip1: 'Learn Mode is read-first.',
    explanationShort: 'Learn Mode encourages reading before the quiz.',
    references: ['JavaScriptopia: Learn vs Challenge'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-welcome',
    answerDocBlockAnchor: 'learn-vs-challenge',
  },
  {
    slug: 'prologue-final-teleport',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What does Teleport to Explanation do?',
    choices: [
      { id: 'a', text: 'Deletes the question' },
      { id: 'b', text: 'Jumps to the exact doc block for the question' },
      { id: 'c', text: 'Resets your score' },
      { id: 'd', text: 'Skips the lesson' },
    ],
    answer: 'b',
    tip1: 'It takes you to the right explanation.',
    explanationShort: 'Teleport jumps to the exact doc block that explains the question.',
    references: ['JavaScriptopia: Teleport'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-welcome',
    answerDocBlockAnchor: 'teleport-explanation',
  },
  {
    slug: 'prologue-final-browser-wars-era',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'The first Browser War happened roughly during:',
    choices: [
      { id: 'a', text: '1975–1980' },
      { id: 'b', text: '1995–2001' },
      { id: 'c', text: '2008–2012' },
      { id: 'd', text: '2015–2020' },
    ],
    answer: 'b',
    tip1: 'Mid-90s to early 2000s.',
    explanationShort: 'The first Browser War is roughly 1995–2001.',
    references: ['Browser wars'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-browser-wars',
    answerDocBlockAnchor: 'browser-wars-intro',
  },
  {
    slug: 'prologue-final-browser-wars-protagonists',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which two companies were the main protagonists of the first Browser War?',
    choices: [
      { id: 'a', text: 'Apple and Google' },
      { id: 'b', text: 'Microsoft and Netscape' },
      { id: 'c', text: 'Yahoo and Meta' },
      { id: 'd', text: 'IBM and Intel' },
    ],
    answer: 'b',
    tip1: 'Navigator vs Internet Explorer.',
    explanationShort: 'Microsoft and Netscape were the key rivals.',
    references: ['Browser wars'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-browser-wars',
    answerDocBlockAnchor: 'browser-wars-protagonists',
  },
  {
    slug: 'prologue-final-why-it-mattered',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Why did the Browser Wars matter to the web?',
    choices: [
      { id: 'a', text: 'They stopped JavaScript development' },
      { id: 'b', text: 'They shaped distribution and standards' },
      { id: 'c', text: 'They eliminated browsers' },
      { id: 'd', text: 'They replaced HTML with CSS' },
    ],
    answer: 'b',
    tip1: 'Think standards and browser evolution.',
    explanationShort: 'They shaped distribution and standards, influencing how the web evolved.',
    references: ['Browser wars'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-browser-wars',
    answerDocBlockAnchor: 'why-it-mattered',
  },
  {
    slug: 'prologue-final-what-is-browser',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'At a high level, what is a browser?',
    choices: [
      { id: 'a', text: 'A text editor' },
      { id: 'b', text: 'An app that loads pages and runs JS' },
      { id: 'c', text: 'A database server' },
      { id: 'd', text: 'A CSS framework' },
    ],
    answer: 'b',
    tip1: 'It runs JS and shows pages.',
    explanationShort: 'A browser loads pages, runs JS, and updates the screen.',
    references: ['JavaScriptopia: Browser'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-where-js-lives',
    answerDocBlockAnchor: 'what-is-a-browser',
  },
  {
    slug: 'prologue-final-js-in-browser',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Where does browser JavaScript usually start?',
    choices: [
      { id: 'a', text: 'In a script tag or module' },
      { id: 'b', text: 'Inside a database' },
      { id: 'c', text: 'Only in CSS files' },
      { id: 'd', text: 'In a spreadsheet' },
    ],
    answer: 'a',
    tip1: 'Think script tags.',
    explanationShort: 'Browser JS usually starts in script tags or modules.',
    references: ['JavaScriptopia: JS in browser'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-where-js-lives',
    answerDocBlockAnchor: 'js-in-the-browser',
  },
  {
    slug: 'prologue-final-js-on-server',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which environment is commonly used for server-side JavaScript?',
    choices: [
      { id: 'a', text: 'Node' },
      { id: 'b', text: 'Photoshop' },
      { id: 'c', text: 'Excel' },
      { id: 'd', text: 'PowerPoint' },
    ],
    answer: 'a',
    tip1: 'Think server-side runtime.',
    explanationShort: 'Node is the common server-side JavaScript environment.',
    references: ['Node.js'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-where-js-lives',
    answerDocBlockAnchor: 'js-on-the-server',
  },
  {
    slug: 'prologue-final-environments-summary',
    difficulty: 'medium',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What stays the same when JavaScript runs in different environments?',
    choices: [
      { id: 'a', text: 'The language is the same, APIs can differ' },
      { id: 'b', text: 'The APIs are always identical' },
      { id: 'c', text: 'Only the syntax changes' },
      { id: 'd', text: 'JavaScript becomes a different language' },
    ],
    answer: 'a',
    tip1: 'Language same, APIs vary.',
    explanationShort: 'JavaScript is the same language, but APIs differ by environment.',
    references: ['JavaScriptopia: Environments'],
    docPageSlug: 'javascriptopia-vanillaland-foundations/prologue-browser-wars/prologue-where-js-lives',
    answerDocBlockAnchor: 'environments-summary',
  },
] as const

export const prologueRuntimeQuestions = [
  {
    slug: 'prologue-runtime-what-is-runtime',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is a JavaScript runtime?',
    choices: [
      { id: 'a', text: 'A database schema' },
      { id: 'b', text: 'The environment that runs JS and provides APIs' },
      { id: 'c', text: 'A CSS preprocessor' },
      { id: 'd', text: 'A UI library' },
    ],
    answer: 'b',
    tip1: 'Think engine + APIs.',
    tip2: 'It is the world your code runs in.',
    explanationShort: 'A runtime runs JavaScript and provides environment APIs.',
    references: ['MDN: JavaScript runtime'],
    answerDocBlockAnchor: 'what-is-runtime',
  },
  {
    slug: 'prologue-runtime-browser-vs-node',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which runtime provides the DOM API?',
    choices: [
      { id: 'a', text: 'Node' },
      { id: 'b', text: 'Browser' },
      { id: 'c', text: 'Git' },
      { id: 'd', text: 'Command line' },
    ],
    answer: 'b',
    tip1: 'DOM stands for Document Object Model.',
    tip2: 'This is a browser feature.',
    explanationShort: 'The browser runtime provides the DOM.',
    references: ['MDN: DOM'],
    answerDocBlockAnchor: 'browser-runtime-vs-node-runtime',
  },
  {
    slug: 'prologue-runtime-api-difference',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which API is typical for Node rather than the browser?',
    choices: [
      { id: 'a', text: 'document.querySelector' },
      { id: 'b', text: 'window.alert' },
      { id: 'c', text: 'fs.readFile' },
      { id: 'd', text: 'addEventListener' },
    ],
    answer: 'c',
    tip1: 'File system access is server-side.',
    tip2: 'Browser does not read local files directly.',
    explanationShort: 'fs.readFile is a Node API.',
    references: ['Node.js: fs'],
    answerDocBlockAnchor: 'apis-provided-by-runtime',
  },
  {
    slug: 'prologue-runtime-mistake',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is a common runtime mistake?',
    choices: [
      { id: 'a', text: 'Assuming APIs are identical everywhere' },
      { id: 'b', text: 'Using variables' },
      { id: 'c', text: 'Writing functions' },
      { id: 'd', text: 'Adding comments' },
    ],
    answer: 'a',
    tip1: 'Think about browser vs Node.',
    tip2: 'APIs differ by environment.',
    explanationShort: 'JavaScript APIs differ by runtime, so assumptions can break code.',
    references: ['MDN: JavaScript environments'],
    answerDocBlockAnchor: 'common-mistakes',
  },
  {
    slug: 'prologue-runtime-typeof-output',
    difficulty: 'basic',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'console.log(typeof \"hello\");',
    answer: 'string',
    tip1: 'typeof returns a lowercase label.',
    tip2: 'Strings are \"string\".',
    explanationShort: 'typeof \"hello\" returns \"string\".',
    references: ['MDN: typeof operator'],
    answerDocBlockAnchor: 'what-is-runtime',
  },
] as const

export const prologueLoopQuestions = [
  {
    slug: 'prologue-loop-what-is-loop',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is the event loop?',
    choices: [
      { id: 'a', text: 'A database query' },
      { id: 'b', text: 'A scheduler that runs queued tasks' },
      { id: 'c', text: 'A CSS animation' },
      { id: 'd', text: 'A JS keyword' },
    ],
    answer: 'b',
    tip1: 'It decides what runs next.',
    tip2: 'Think scheduler.',
    explanationShort: 'The event loop schedules tasks and microtasks to run.',
    references: ['javascript.info: Event loop'],
    answerDocBlockAnchor: 'the-loop-in-one-minute',
  },
  {
    slug: 'prologue-loop-call-stack',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What does the call stack track?',
    choices: [
      { id: 'a', text: 'Open browser tabs' },
      { id: 'b', text: 'Functions currently executing' },
      { id: 'c', text: 'Downloaded files' },
      { id: 'd', text: 'Git commits' },
    ],
    answer: 'b',
    tip1: 'Think function order.',
    tip2: 'It is a stack of calls.',
    explanationShort: 'The call stack stores the active function calls.',
    references: ['MDN: Call stack'],
    answerDocBlockAnchor: 'call-stack',
  },
  {
    slug: 'prologue-loop-microtasks',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Microtasks typically come from:',
    choices: [
      { id: 'a', text: 'setTimeout callbacks' },
      { id: 'b', text: 'Promise callbacks' },
      { id: 'c', text: 'CSS transitions' },
      { id: 'd', text: 'HTML parsing' },
    ],
    answer: 'b',
    tip1: 'Promises queue microtasks.',
    tip2: 'Then/catch callbacks are microtasks.',
    explanationShort: 'Promise callbacks run in the microtask queue.',
    references: ['javascript.info: Event loop'],
    answerDocBlockAnchor: 'microtask-queue',
  },
  {
    slug: 'prologue-loop-task-queue',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which is an example of a task?',
    choices: [
      { id: 'a', text: 'Promise.then' },
      { id: 'b', text: 'setTimeout callback' },
      { id: 'c', text: 'A synchronous function call' },
      { id: 'd', text: 'A variable assignment' },
    ],
    answer: 'b',
    tip1: 'Timers schedule tasks.',
    tip2: 'Microtasks are from Promises.',
    explanationShort: 'setTimeout callbacks are tasks.',
    references: ['MDN: setTimeout'],
    answerDocBlockAnchor: 'task-queue',
  },
  {
    slug: 'prologue-loop-order',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'console.log(\"A\");\nsetTimeout(() => console.log(\"B\"), 0);\nPromise.resolve().then(() => console.log(\"C\"));\nconsole.log(\"D\");',
    answer: 'A\nD\nC\nB',
    tip1: 'Sync first, microtasks next, tasks last.',
    tip2: 'Promises run before timers.',
    explanationShort: 'Order is A, D, C, B.',
    references: ['javascript.info: Event loop'],
    answerDocBlockAnchor: 'microtasks-vs-tasks-example',
  },
  {
    slug: 'prologue-loop-why-matters',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Why does the event loop matter?',
    choices: [
      { id: 'a', text: 'It sets CSS colors' },
      { id: 'b', text: 'It helps predict async timing' },
      { id: 'c', text: 'It replaces HTML' },
      { id: 'd', text: 'It stores images' },
    ],
    answer: 'b',
    tip1: 'Think async order.',
    tip2: 'It prevents surprises in timing.',
    explanationShort: 'The event loop explains async execution order.',
    references: ['javascript.info: Event loop'],
    answerDocBlockAnchor: 'why-this-matters',
  },
] as const

export const prologueWhereQuestions = [
  {
    slug: 'prologue-where-browser',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What does a browser do besides running JS?',
    choices: [
      { id: 'a', text: 'Renders HTML/CSS and updates the screen' },
      { id: 'b', text: 'Compiles C code' },
      { id: 'c', text: 'Only runs databases' },
      { id: 'd', text: 'Only stores images' },
    ],
    answer: 'a',
    tip1: 'Browsers render pages.',
    tip2: 'They include a rendering engine.',
    explanationShort: 'Browsers render HTML/CSS and update the UI.',
    references: ['HTML Standard'],
    answerDocBlockAnchor: 'what-is-a-browser',
  },
  {
    slug: 'prologue-where-script-tag',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'How do browsers commonly load JS?',
    choices: [
      { id: 'a', text: 'Using a script tag or module' },
      { id: 'b', text: 'Using SQL' },
      { id: 'c', text: 'Using CSS only' },
      { id: 'd', text: 'Using git commits' },
    ],
    answer: 'a',
    tip1: 'Think HTML tags.',
    tip2: 'Scripts are loaded by the browser.',
    explanationShort: 'Browsers load JS with script tags or modules.',
    references: ['MDN: script'],
    answerDocBlockAnchor: 'js-in-the-browser',
  },
  {
    slug: 'prologue-where-node',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Node is best described as:',
    choices: [
      { id: 'a', text: 'A browser extension' },
      { id: 'b', text: 'A JavaScript runtime outside the browser' },
      { id: 'c', text: 'A CSS framework' },
      { id: 'd', text: 'A database engine' },
    ],
    answer: 'b',
    tip1: 'It runs JS on the server.',
    tip2: 'It is not a browser.',
    explanationShort: 'Node is a JavaScript runtime outside the browser.',
    references: ['Node.js'],
    answerDocBlockAnchor: 'js-on-the-server',
  },
  {
    slug: 'prologue-where-other-runtimes',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which is an example of another JS runtime?',
    choices: [
      { id: 'a', text: 'Deno' },
      { id: 'b', text: 'Photoshop' },
      { id: 'c', text: 'Git' },
      { id: 'd', text: 'Chrome bookmarks' },
    ],
    answer: 'a',
    tip1: 'It is a JS runtime like Node.',
    tip2: 'It is built for modern JS.',
    explanationShort: 'Deno is a JavaScript runtime.',
    references: ['Deno'],
    answerDocBlockAnchor: 'other-runtimes',
  },
  {
    slug: 'prologue-where-apis',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which environment provides DOM APIs?',
    choices: [
      { id: 'a', text: 'Browser' },
      { id: 'b', text: 'Node' },
      { id: 'c', text: 'Git' },
      { id: 'd', text: 'Command line' },
    ],
    answer: 'a',
    tip1: 'DOM is for web pages.',
    tip2: 'It is provided by browsers.',
    explanationShort: 'Browsers provide DOM APIs.',
    references: ['MDN: DOM'],
    answerDocBlockAnchor: 'js-in-the-browser',
  },
] as const

export const prologueCommandlineQuestions = [
  {
    slug: 'prologue-cli-what-is-cli',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is the command line?',
    choices: [
      { id: 'a', text: 'A text interface to your computer' },
      { id: 'b', text: 'A browser tab' },
      { id: 'c', text: 'A video editor' },
      { id: 'd', text: 'A keyboard shortcut' },
    ],
    answer: 'a',
    tip1: 'You type commands.',
    tip2: 'It is a text interface.',
    explanationShort: 'The command line is a text interface for your computer.',
    references: ['CLI basics'],
    answerDocBlockAnchor: 'what-is-command-line',
  },
  {
    slug: 'prologue-cli-why-use',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Why do developers use the CLI?',
    choices: [
      { id: 'a', text: 'It is scriptable and fast' },
      { id: 'b', text: 'It replaces JavaScript' },
      { id: 'c', text: 'It only works for games' },
      { id: 'd', text: 'It is required for CSS' },
    ],
    answer: 'a',
    tip1: 'Think automation.',
    tip2: 'It is efficient for repeated tasks.',
    explanationShort: 'CLI is fast, scriptable, and great for automation.',
    references: ['CLI basics'],
    answerDocBlockAnchor: 'why-devs-use-cli',
  },
  {
    slug: 'prologue-cli-repl',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is the Node REPL?',
    choices: [
      { id: 'a', text: 'A text editor' },
      { id: 'b', text: 'An interactive JS console' },
      { id: 'c', text: 'A package manager' },
      { id: 'd', text: 'A browser engine' },
    ],
    answer: 'b',
    tip1: 'It lets you type JS and see results.',
    tip2: 'Think interactive console.',
    explanationShort: 'The REPL is an interactive JavaScript console in Node.',
    references: ['Node.js REPL'],
    answerDocBlockAnchor: 'node-repl-and-running-files',
  },
  {
    slug: 'prologue-cli-packages',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is a package in JavaScript?',
    choices: [
      { id: 'a', text: 'Reusable code shared by the community' },
      { id: 'b', text: 'A CSS file' },
      { id: 'c', text: 'A browser cookie' },
      { id: 'd', text: 'A console theme' },
    ],
    answer: 'a',
    tip1: 'Think reusable modules.',
    tip2: 'They are shared via package managers.',
    explanationShort: 'Packages are reusable code modules shared in the ecosystem.',
    references: ['npm'],
    answerDocBlockAnchor: 'packages-high-level',
  },
  {
    slug: 'prologue-cli-mothership',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'In the lore, the CommandLine is described as:',
    choices: [
      { id: 'a', text: 'A toy' },
      { id: 'b', text: 'The mothership' },
      { id: 'c', text: 'A browser tab' },
      { id: 'd', text: 'A chatbot' },
    ],
    answer: 'b',
    tip1: 'It is a big central tool.',
    tip2: 'Think mothership.',
    explanationShort: 'CommandLine is the mothership that builds and repairs ships.',
    references: ['JavaScriptopia: Prologue'],
    answerDocBlockAnchor: 'lore-commandline-mothership',
  },
] as const

export const prologueGitQuestions = [
  {
    slug: 'prologue-git-what-is-git',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is Git?',
    choices: [
      { id: 'a', text: 'A version control system' },
      { id: 'b', text: 'A web browser' },
      { id: 'c', text: 'A CSS framework' },
      { id: 'd', text: 'A database engine' },
    ],
    answer: 'a',
    tip1: 'It tracks history.',
    tip2: 'It saves changes over time.',
    explanationShort: 'Git is a version control system for tracking changes.',
    references: ['Git'],
    answerDocBlockAnchor: 'what-is-git',
  },
  {
    slug: 'prologue-git-commit',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'A commit is best described as:',
    choices: [
      { id: 'a', text: 'A snapshot of your project' },
      { id: 'b', text: 'A browser tab' },
      { id: 'c', text: 'A CSS selector' },
      { id: 'd', text: 'A running process' },
    ],
    answer: 'a',
    tip1: 'Think saved history.',
    tip2: 'It captures a moment in time.',
    explanationShort: 'A commit is a snapshot of your project at a moment in time.',
    references: ['Git'],
    answerDocBlockAnchor: 'commit-as-snapshot',
  },
  {
    slug: 'prologue-git-branch',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'A branch is best described as:',
    choices: [
      { id: 'a', text: 'A timeline of changes' },
      { id: 'b', text: 'A file extension' },
      { id: 'c', text: 'A database table' },
      { id: 'd', text: 'A browser cookie' },
    ],
    answer: 'a',
    tip1: 'It is a line of development.',
    tip2: 'It lets you experiment safely.',
    explanationShort: 'A branch is a timeline of changes you can work on independently.',
    references: ['Git'],
    answerDocBlockAnchor: 'branch-as-timeline',
  },
  {
    slug: 'prologue-git-remote',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'What is a remote in Git?',
    choices: [
      { id: 'a', text: 'A copy of the repo stored elsewhere' },
      { id: 'b', text: 'A local folder only' },
      { id: 'c', text: 'A JavaScript runtime' },
      { id: 'd', text: 'A browser cache' },
    ],
    answer: 'a',
    tip1: 'It lives outside your machine.',
    tip2: 'Teams use it to share code.',
    explanationShort: 'A remote is a copy of the repo stored elsewhere for sharing.',
    references: ['Git'],
    answerDocBlockAnchor: 'remote-and-origin',
  },
  {
    slug: 'prologue-git-mistake',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'A common Git mistake is:',
    choices: [
      { id: 'a', text: 'Forgetting to commit' },
      { id: 'b', text: 'Writing comments' },
      { id: 'c', text: 'Using camelCase' },
      { id: 'd', text: 'Reading documentation' },
    ],
    answer: 'a',
    tip1: 'Think missing history.',
    tip2: 'Small commits help clarity.',
    explanationShort: 'Forgetting to commit leaves you without clear history.',
    references: ['Git'],
    answerDocBlockAnchor: 'common-mistakes',
  },
  {
    slug: 'prologue-git-branch-purpose',
    difficulty: 'medium',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Why use a branch before a risky change?',
    choices: [
      { id: 'a', text: 'To avoid breaking main' },
      { id: 'b', text: 'To remove history' },
      { id: 'c', text: 'To run CSS faster' },
      { id: 'd', text: 'To delete commits' },
    ],
    answer: 'a',
    tip1: 'Branches isolate experiments.',
    tip2: 'You can merge later.',
    explanationShort: 'Branches let you experiment without breaking main.',
    references: ['Git'],
    answerDocBlockAnchor: 'branch-as-timeline',
  },
] as const

export const prologueTrialQuestions = [
  {
    slug: 'prologue-trial-browser-wars',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'The Browser Wars influenced the web by:',
    choices: [
      { id: 'a', text: 'Shaping browser competition and standards' },
      { id: 'b', text: 'Ending JavaScript' },
      { id: 'c', text: 'Removing HTML' },
      { id: 'd', text: 'Replacing browsers with servers' },
    ],
    answer: 'a',
    tip1: 'Think competition and standards.',
    tip2: 'It shaped how browsers evolved.',
    explanationShort: 'Browser competition influenced standards and the web ecosystem.',
    references: ['DOJ Complaint: U.S. v. Microsoft'],
    answerDocBlockAnchor: 'trial-rules',
  },
  {
    slug: 'prologue-trial-runtime-vs-loop',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which statement is true?',
    choices: [
      { id: 'a', text: 'Runtime is the environment; loop is the scheduler' },
      { id: 'b', text: 'Loop is the environment; runtime is a JS keyword' },
      { id: 'c', text: 'Both are CSS concepts' },
      { id: 'd', text: 'Both are file formats' },
    ],
    answer: 'a',
    tip1: 'Runtime = environment.',
    tip2: 'Loop = scheduler.',
    explanationShort: 'Runtime is the environment; loop schedules execution.',
    references: ['JavaScriptopia: Prologue'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-call-stack',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'The call stack stores:',
    choices: [
      { id: 'a', text: 'Active function calls' },
      { id: 'b', text: 'Downloaded images' },
      { id: 'c', text: 'Git commits' },
      { id: 'd', text: 'CSS variables' },
    ],
    answer: 'a',
    tip1: 'Think function order.',
    tip2: 'It is a stack of calls.',
    explanationShort: 'The call stack keeps track of active function calls.',
    references: ['MDN: Call stack'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-microtasks',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Promise callbacks are placed in the:',
    choices: [
      { id: 'a', text: 'Microtask queue' },
      { id: 'b', text: 'Task queue' },
      { id: 'c', text: 'Call stack' },
      { id: 'd', text: 'CSS queue' },
    ],
    answer: 'a',
    tip1: 'Promises are microtasks.',
    tip2: 'They run before tasks.',
    explanationShort: 'Promise callbacks are scheduled in the microtask queue.',
    references: ['javascript.info: Event loop'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-browser-vs-node',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which environment provides the DOM?',
    choices: [
      { id: 'a', text: 'Browser' },
      { id: 'b', text: 'Node' },
      { id: 'c', text: 'Git' },
      { id: 'd', text: 'CLI' },
    ],
    answer: 'a',
    tip1: 'DOM is for pages.',
    tip2: 'Browsers provide it.',
    explanationShort: 'Browsers provide the DOM APIs.',
    references: ['MDN: DOM'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-cli-purpose',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'The command line is used to:',
    choices: [
      { id: 'a', text: 'Run commands and automate tasks' },
      { id: 'b', text: 'Replace HTML' },
      { id: 'c', text: 'Draw UI only' },
      { id: 'd', text: 'Store images' },
    ],
    answer: 'a',
    tip1: 'Think automation.',
    tip2: 'It is a text interface.',
    explanationShort: 'The command line runs commands and automates tasks.',
    references: ['CLI basics'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-git-commit',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'A Git commit is:',
    choices: [
      { id: 'a', text: 'A snapshot of the project' },
      { id: 'b', text: 'A browser tab' },
      { id: 'c', text: 'A runtime API' },
      { id: 'd', text: 'A CSS selector' },
    ],
    answer: 'a',
    tip1: 'Think saved history.',
    tip2: 'It is a snapshot.',
    explanationShort: 'A commit saves a snapshot of the project.',
    references: ['Git'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-branch',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'A Git branch is:',
    choices: [
      { id: 'a', text: 'A timeline of changes' },
      { id: 'b', text: 'A text editor' },
      { id: 'c', text: 'A runtime' },
      { id: 'd', text: 'A browser cache' },
    ],
    answer: 'a',
    tip1: 'Think parallel timeline.',
    tip2: 'It is a line of development.',
    explanationShort: 'A branch is a separate timeline of changes.',
    references: ['Git'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-runtime',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'A runtime provides:',
    choices: [
      { id: 'a', text: 'Execution environment and APIs' },
      { id: 'b', text: 'Only CSS' },
      { id: 'c', text: 'Only HTML' },
      { id: 'd', text: 'Only database tables' },
    ],
    answer: 'a',
    tip1: 'Engine plus APIs.',
    tip2: 'Environment matters.',
    explanationShort: 'A runtime provides the environment and its APIs.',
    references: ['MDN: JavaScript runtime'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-loop-order',
    difficulty: 'medium',
    type: 'code_output',
    phase: 'quiz',
    prompt: 'What does this code print?',
    code: 'console.log(\"A\");\nPromise.resolve().then(() => console.log(\"B\"));\nsetTimeout(() => console.log(\"C\"), 0);\nconsole.log(\"D\");',
    answer: 'A\nD\nB\nC',
    tip1: 'Microtasks before tasks.',
    tip2: 'Sync first, then microtasks.',
    explanationShort: 'Order is A, D, B, C.',
    references: ['javascript.info: Event loop'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-browser',
    difficulty: 'basic',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Which best describes a browser?',
    choices: [
      { id: 'a', text: 'A runtime that renders HTML/CSS and runs JS' },
      { id: 'b', text: 'A database engine' },
      { id: 'c', text: 'A package manager' },
      { id: 'd', text: 'A text editor only' },
    ],
    answer: 'a',
    tip1: 'It renders pages and runs JS.',
    tip2: 'It includes a rendering engine.',
    explanationShort: 'A browser renders HTML/CSS and runs JS with web APIs.',
    references: ['HTML Standard'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
  {
    slug: 'prologue-trial-cli',
    difficulty: 'medium',
    type: 'mcq',
    phase: 'quiz',
    prompt: 'Why is the CLI described as the mothership?',
    choices: [
      { id: 'a', text: 'It builds and repairs ships (projects)' },
      { id: 'b', text: 'It is only for games' },
      { id: 'c', text: 'It replaces the browser' },
      { id: 'd', text: 'It is a database' },
    ],
    answer: 'a',
    tip1: 'Think central tool.',
    tip2: 'It builds projects quickly.',
    explanationShort: 'The CLI is the central tool that builds and maintains projects.',
    references: ['JavaScriptopia: Prologue'],
    answerDocBlockAnchor: 'what-you-should-know',
  },
] as const
